### ISSUE TITLE
Errors after finding relevant tweet

### ISSUE THREAD

**Issue by Lippa73** [PraneshASP/crypto-trading-bot#1]
**After coming across a positive sentiment tweet I get the following output**

Results [
    {
        "text": "Bitcoin please do great things. Christmas is coming",
        "sentiment": "POSITIVE",
        "tweetId": "1465614838575546374"
    }
]

**but then get this error message**

[ 'balanceData error', {} ]
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function 
without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<IncomingMessage>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

**After coming across a Negative sentiment tweet I get this output**

tweets [ { id: '1465624391555989508', text: 'bitcoin is bad' } ]
Results [
    {
        "text": "bitcoin is bad",
        "sentiment": "NEGATIVE",
        "tweetId": "1465624391555989508"
    }
]

**and then this error**
[ 'balanceData error', {} ]
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function 
without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<IncomingMessage>".] {
  code: 'ERR_UNHANDLED_REJECTION'

**and after finding a neutral sentiment tweet I get this output**

tweets [
  {
    id: '1465623828592275456',
  }
]
Results []

**and this error**

C:\Users\Owner\crypto-trading-bot-main\app.js:81
    fs.writeFileSync("./tweetId.txt", tweets[tweets.length].tweetId);
                                                            ^

TypeError: Cannot read properties of undefined (reading 'tweetId')
    at startProcessing (C:\Users\Owner\crypto-trading-bot-main\app.js:81:61)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Timeout._onTimeout (C:\Users\Owner\crypto-trading-bot-main\app.js:89:5)

**Comment by Lippa73** [comment]
My bad - had a space before my api key in the env file
